### ISSUE TITLE
Import en export van case definities

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [generiekzaakafhandelcomponent/roadmap-items#17]
Ingebracht door @rutger-h 

## Doel

Bij het bouwen van processen zijn er twee gebruikersgroepen te onderscheiden, de no-coders en de developers.

Het droomdoel is om zonder code (‘no code’) business processen te bouwen, om zo geen developers te hebben. Eenvoudige processen worden via de User Interface in basis geconfigureerd door beheerders, business analisten en lowcoders. In praktijk blijkt dat dev’s nodig zijn bij complexere bedrijfsprocessen of aanvullingen op het werk van de eerste groep. Deze groep werkt via een IDE, de integrated development environment - 'code'. 

Het doel is om deze twee gebruikersgroepen naadloos te laten samenwerken.  

## Context / achtergrond

1. De Software Improvement Group heeft tijdens het onderzoek naar OpenZaak en GZAC aangegegeven dat a) er nooit handmatig wijzigingen gemaakt moeten worden op een productieomgeving en er een CD-pipeline nodig in een OTAP setup. Daarnaast kan kwaliteit beter gegarandeerd worden als er unit tests worden gedraaid bij elke verandering - en daarmee een CI-pipeline. 

Handmatige wijzigingen in de beheeromgeving zijn foutgevoelig en onwenselijk in productiesystemen. De beheerder moet al het werk meerdere malen doen, op alle omgevingen. In het onderzoek van de Software Improvement Group wordt dit afgeraden te doen. Wijzigingen op productie moeten (net zoals bij de developer doelgroep) via de OTAP-straat worden gedaan, waarbij garanties worden geboden in kwaliteit (waaronder security en beschikbaarheid) door de buildstraat. 

Bovenstaande maakt dat configuratie in code vast moet liggen. De no-coders kunnen dat nu niet - hun configuratie ligt in de database vast. De wens is dat ook deze doelgroep het resultaat van hun werk in code kunnen vastleggen op een repository. 

2. De beiden doelgroepen kunnen nu niet samenwerken op een proces. De files (bijvoorbeeld BPMN) in een repositoy overschrijven de files in de database, en daarmee 'wint' de developer als er conflicten zijn. 

## Wat moet er gebeuren - wat is er nog niet en hebben we wel nodig?
1. Mogelijheid om een zip te exporteren/importen met alle config-files. 

## Wat is het eindresultaat?

Significant toegankelijker systeem voor gebruikers als Utrecht Versterken Common Ground, Den Haag beheerders, de eerste gebruikers van Tilburg en de wensen van Leeuwarden. 

## Wat valt er buiten scope?
1. Een setting 'beheermodus' / 'production-modus' - die de adminschermen uitschakelt, zodat beheerders niet werken op een systeem waarop developers ook actief zijn.
2. Mogelijkheid om vanuit de UI als beheerder een 'push' te doen naar Github van het betreffende project.  

## Impact - hoeveel inspanning kost dit? 
Inschatting door PO: S/M/L/XL  
Inschatting door SA: S/M/L/XL

**Comment by ThomasMinkeRitense** [comment]
Gevraagd: losse inschatting voor alle punten

**Comment by SjorsDriessen** [comment]
Hoi, ik vroeg mij af wat de status van dit item is. Ik zie hem niet terugkomen in airfocus of in de sprint reviews. Wordt hier nog aan gewerkt?

**Comment by rutger-h** [comment]
@ThomasMinkeRitense

**Comment by ThomasMinkeRitense** [comment]
@SjorsDriessen Goed punt. We hebben vorig jaar dit issue gesplitst in twee delen. Deel 1, de import en export, is vorige week gereleased in versie 11.2. Deel twee en drie, de beheermodus en Git integratie zijn nog niet gemaakt en zijn op dit moment ook niet gepland. Ik ga een nieuw issue aanmaken en deze aanpassen.
